version: "3.9"
services:
  postgres:
    build: ./build
    image: postgres:15
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"

  web:
    build:
      context: .
      dockerfile: "./Dockerfile"
    ports:
      - "8000:8000"
    depends_on:
      - postgres